[toolchain]

[features]
resolution = true
skip-lint = true

[programs.devnet]
advanced_oracle_example = "DKpZoRdw6CkbQPCLuyeQsgLCh3kSaYKhGZ6fvgJCTMgr"
basic_oracle_example = "4ZK7w1R7R4GJrFBSUZrNPnmzsUeG8bvVKvk6z7bvQ2zZ"
sb_randomness = "44wNsyMPUQxCDhJpKqwNu8XGjqYbThqgRPUpQCARyrUc"

[programs.mainnet]
advanced_oracle_example = "FNnhcuzFqg8CSVHRauPh8rFaqSrJzsQ8wL66GFL8VJZQ"
basic_oracle_example = "C4KQQeJVJ1X4uP2XeRGJT77s6A9ooas8rZiW1XB2C2r8"
sb_randomness = "44wNsyMPUQxCDhJpKqwNu8XGjqYbThqgRPUpQCARyrUc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
