[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
sb_on_demand_solana = "2uGHnRkDsupNnicE3btnqJbpus7DWKuniZcRmKAzHFv5"

[programs.mainnet]
sb_on_demand_solana = "2peDtg8dVTwnoUmh45zstq7C7sFo5hdt4KHnAAPGNNdy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
