[toolchain]

[features]
resolution = true
skip-lint = true

[programs.devnet]
sb_on_demand_solana = "2uGHnRkDsupNnicE3btnqJbpus7DWKuniZcRmKAzHFv5"

[programs.mainnet]
sb_on_demand_solana = "GXiCkAx51V9FPfH68Pz7AT7ZCK4xrrWQmXgvHtMtvfqU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
