[toolchain]

[features]
resolution = true
skip-lint = true

[programs.devnet]
sb_randomness = "twKsQnuRXRC9qHgwXfiMMU8qHKzr6qUjW7hkd86ABgW"

[programs.mainnet]
sb_randomness = "twKsQnuRXRC9qHgwXfiMMU8qHKzr6qUjW7hkd86ABgW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "~/.config/solana/id.json"
