[toolchain]

[features]
resolution = true
skip-lint = true

[programs.devnet]
sb_randomness = "Dqq2Daxxnb7pEiJMVQ7UnJ973pJCtg8B5FRN6v58cU3r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
